#!/bin/bash

VERSION="5.0.1"

# Customer customization: change this block for white-label builds.
APP_NAME="RustMinerSystem"
APP_ID="rustminersystem"
DOWNLOAD_HOST="https://github.com/EvilGenius-dot/RustMinerSystem/raw/main/linux"
CLI_DOWNLOAD_URL="https://github.com/EvilGenius-dot/RustMinerSystem/raw/refs/heads/main/CLI/RustMinerSystemCLI-0.1.0"

SERVICE_NAME="rustservice"
PROCESS_WAIT_INTERVAL="0.1"
PROCESS_WAIT_STEPS_PER_SECOND=10
PROCESS_WAIT_INTERVAL_SUPPORTED=""

PATH_RUST="/root/${APP_ID}"
PATH_EXEC="${APP_ID}"
DOWNLOAD_EXEC_PREFIX="${PATH_EXEC}"
ORIGIN_EXEC="${DOWNLOAD_EXEC_PREFIX}-${VERSION}"
CLI_EXEC_NAME="RustMinerSystemCLI-0.1.0"
CLI_COMMAND_NAME="rustminer"
CLI_LINK_PATH="/usr/local/bin/${CLI_COMMAND_NAME}"
CLI_LAUNCHER_MARKER="Generated by RustMinerSystem install.sh"
CONFIG_FILE_NAME="rust-config"
SYSCTL_TAG="${APP_ID}"
INSTALL_DIR_GUARD="${APP_ID}"

PATH_CONFIG="${PATH_RUST}/${CONFIG_FILE_NAME}"
PATH_NOHUP="${PATH_RUST}/nohup.out"
PATH_ERR="${PATH_RUST}/err.log"
PATH_CUE="${PATH_RUST}/cue"
PATH_D_1="${PATH_RUST}/0.d1"
PATH_D_2="${PATH_RUST}/0.d1-shm"
PATH_D_3="${PATH_RUST}/0.d1-wal"
PATH_CLI="${PATH_RUST}/${CLI_EXEC_NAME}"
PATH_CLI_TMP="${PATH_RUST}/${CLI_EXEC_NAME}.tmp"

RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
BOLD="\033[1m"
RESET="\033[0m"


# -----------------------------------------------------------------------------
# Language text
# -----------------------------------------------------------------------------

select_language() {
    clear
    echo "Please select your language / 请选择语言:"
    echo "1. English"
    echo "2. 中文"
    read -p "$(echo -e "[1-2]：")" lang_choice
}

load_language() {
    case "$lang_choice" in
    1)
        prompt_install="1. Install"
        prompt_update="2. Update"
        prompt_target_version="3. Install version"
        prompt_start="4. Start"
        prompt_stop="5. Stop"
        prompt_restart="6. Restart"
        prompt_port="7. Change port"
        prompt_ulimit="8. Raise Linux connection limit"
        prompt_https="9. HTTPS access"
        prompt_enable_web_ui="10. Enable WEB access"
        prompt_disable_web_ui="11. Disable WEB access"
        prompt_auto_start="12. Enable autostart"
        prompt_disable_auto_start="13. Disable autostart"
        prompt_service_log="14. View systemd service log"
        prompt_status="15. View runtime log"
        prompt_error_log="16. View error log"
        prompt_clear_log="17. Clear logs"
        prompt_web_port="18. View WEB port"
        prompt_uninstall="19. Uninstall"
        prompt_reset_pwd="20. Reset account password"
        prompt_runtime_status="21. View runtime status"
        prompt_install_cli="22. Install CLI tool"
        prompt_uninstall_cli="23. Uninstall CLI tool"
        prompt_choose_menu="Please choose [1-23]: "
        prompt_choose_short="Please choose"
        prompt_root_no="Please run this script as root!"
        prompt_error_command="Invalid command entered. Please try again."
        prompt_set_port="Enter the port number: "
        prompt_https_question="Enable HTTPS backend access? After enabling it, the backend must be accessed with https://. After disabling it, use http://."
        prompt_https_off="1. Disabled"
        prompt_https_on="2. Enabled"
        prompt_https_choose="Please choose [1-2]: "
        prompt_https_invalid="Invalid input, HTTPS is enabled by default."
        prompt_enter_version="Please enter the version number: "
        prompt_confirm_uninstall="Type YES to confirm uninstall: "
        prompt_confirm_cli_install="Please choose whether to continue CLI installation [1-2]: "
        prompt_confirm_cli_uninstall="Type YES to confirm CLI uninstall: "
        prompt_confirm_web_ui_change="Please choose whether to continue [1-2]: "

        menu_group_install="Install & Update"
        menu_group_runtime="Runtime Control"
        menu_group_settings="Settings"
        menu_group_logs="Log Management"
        menu_group_maintenance="Maintenance"
        menu_group_cli="CLI Tool"
        menu_tip="Tip: Linux connection limit changes require a server restart to take effect."

        msg_install_start="Start installation: "
        msg_disable_firewall="Disable firewall"
        msg_unknown_os_firewall="Unknown operating system, failed to disable firewall"
        msg_starting="Start program"
        msg_already_running="Program is already running, please do not start it again."
        msg_start_failed="Program startup failure!!!"
        msg_started_title="Program started successfully"
        msg_version_label="Version"
        msg_backend_url="Backend access URL"
        msg_default_username="Default username"
        msg_default_password="Default password"
        msg_tip_label="Tip"
        msg_public_firewall_tip="For public backend access, remember to open the provider firewall."
        msg_default_security_tip="If you are using the default password and port, please change the account password and web access port in the web settings."
        msg_http_tip="Current backend uses HTTP. Do not access it with HTTPS. To use HTTPS, run this script and choose 9."
        msg_https_tip="Current backend uses HTTPS. Do not access it with HTTP. To use HTTP, run this script and choose 9."
        msg_delete_config="Delete configuration files"
        msg_password_reset_done="Password reset completed, changed to default account/password: qzpm19kkx xloqslz913"
        msg_terminating="Terminating process..."
        msg_process_not_found="Not found"
        msg_process_label="process"
        msg_process_terminated="Terminated"
        msg_stopping_process="Stopping process"
        msg_stop_timeout="Process did not stop within timeout"
        msg_enable_autostart="Set up automatic startup"
        msg_disable_autostart="Disable automatic startup..."
        msg_failed="Failed"
        msg_config_missing="Environment variable configuration file not found, creating one now"
        msg_config_updated="Updated configuration file"
        msg_config_added="Added configuration to file"
        msg_config_changed="Configuration changed"
        msg_change_limit="Modify system connection limit"
        msg_limit_changed_restart="Connection limit has been changed to 65535, please restart the server for the change to take effect"
        msg_current_limit="Current connection limit:"
        msg_change_done_restart="Modification completed, please restart the server for the change to take effect"
        msg_running_detected="Detected running"
        msg_must_stop_before_install=", it must be stopped before continuing with the installation."
        msg_enter_stop_running="Enter 1 to stop the running"
        msg_or_cancel_install="and continue with the installation, enter 2 to cancel the installation."
        msg_cancel_install="Cancel installation"
        msg_invalid_cancel_install="Invalid input, cancelling installation."
        msg_create_dir="Creating directory"
        msg_dir_exists="Directory already exists, no need to create it again, continuing with the installation."
        msg_downloading="Downloading..."
        msg_download_program="Downloading program"
        msg_download_source="Download source"
        msg_download_target="Save as"
        msg_download_complete="Download completed"
        msg_uninstall_done="Uninstall completed"
        msg_cli_install_start="Installing CLI tool"
        msg_cli_download_program="Downloading CLI tool"
        msg_cli_main_missing="RustMinerSystem is not installed. Please choose 1 to install RustMinerSystem first, then install the CLI tool."
        msg_cli_already_installed="rustminer CLI is already installed."
        msg_cli_command_exists="rustminer command already exists and is not managed by this script"
        msg_cli_install_done_title="CLI tool installed successfully"
        msg_cli_install_done_run="Run rustminer to open the CLI tool. Use rustminer start, rustminer stop, or rustminer restart to control RustMinerSystem."
        msg_cli_install_done_path="CLI path"
        msg_cli_install_done_link="Command launcher"
        msg_cli_install_done_doc="CLI guide/documentation"
        msg_cli_install_warning_title="Before installing the CLI tool, RustMinerSystem WEB access must be disabled."
        msg_cli_install_warning_detail="After WEB access is disabled, the web page will be unreachable and statistics can only be viewed through the CLI tool. To enable or disable WEB access later, run this install script and choose the WEB access option."
        msg_cli_install_continue="1. Continue installation and switch to CLI mode"
        msg_cli_install_cancel="2. Cancel"
        msg_cli_install_cancelled="CLI installation cancelled."
        msg_cli_launching="Opening CLI tool..."
        msg_cli_not_installed="rustminer CLI is not installed."
        msg_cli_uninstall_done="CLI tool uninstalled"
        msg_web_ui_change_notice_title="Changing WEB access will restart RustMinerSystem."
        msg_web_ui_change_notice_detail="If WEB access is disabled, the web page will be unreachable; use the rustminer CLI to access statistics. If the CLI is not installed, install it from this script's menu."
        msg_web_ui_change_continue="1. Continue and restart RustMinerSystem"
        msg_web_ui_change_cancel="2. Cancel"
        msg_web_ui_change_cancelled="WEB access change cancelled."
        msg_web_ui_enabled="WEB access has been enabled."
        msg_web_ui_disabled="WEB access has been disabled."
        msg_web_ui_disabled_start_tip="WEB access is disabled. Run rustminer to open the CLI tool, or enable WEB access from this install script."
        msg_tail_hint="Press CTRL+C to stop viewing logs"
        msg_service_log="Viewing systemd service log"
        msg_journalctl_missing="journalctl was not found. This system may not use systemd."
        msg_service_status_label="Service status"
        msg_status_running="Running"
        msg_status_stopped="Not started"
        msg_status_abnormal="Abnormal"
        msg_status_unavailable="systemd unavailable"
        msg_missing_dependency="Missing required command(s)"
        msg_missing_downloader="Missing downloader: please install wget or curl."
        msg_invalid_port="Invalid port. Please enter a number from 1 to 65535."
        msg_port_in_use="Port is already in use, please choose another one."
        msg_invalid_version="Invalid version. Use only letters, numbers, dot, dash, or underscore."
        msg_uninstall_cancelled="Uninstall cancelled."
        msg_invalid_remove_path="Unsafe remove path detected, operation cancelled"
        msg_limit_global_done="Global network and file descriptor optimization completed."
        msg_limit_reboot_required="Please restart the server for all changes to fully take effect."
        msg_limit_sysctl_missing="sysctl was not found, failed to apply network optimization."
        msg_clear_logs="Cleaning up logs"
        msg_clear_done="Cleanup completed"
        msg_current_web_port="Current WEB access port is"
        msg_enter_release_version="Enter the published version number to install:"
        msg_version_example="Enter the specified version number, for example 3.5.0"
        ;;
    2)
        prompt_install="1. 安装"
        prompt_update="2. 更新"
        prompt_target_version="3. 安装指定版本"
        prompt_start="4. 启动软件"
        prompt_stop="5. 停止软件"
        prompt_restart="6. 重启软件"
        prompt_port="7. 修改端口"
        prompt_ulimit="8. 解除系统连接数限制"
        prompt_https="9. 设置HTTPS访问"
        prompt_enable_web_ui="10. 开启WEB访问"
        prompt_disable_web_ui="11. 关闭WEB访问"
        prompt_auto_start="12. 设置开机启动"
        prompt_disable_auto_start="13. 关闭开机启动"
        prompt_service_log="14. 查看systemd服务日志"
        prompt_status="15. 查看运行日志"
        prompt_error_log="16. 查看错误日志"
        prompt_clear_log="17. 清理日志"
        prompt_web_port="18. 查看WEB端口"
        prompt_uninstall="19. 卸载"
        prompt_reset_pwd="20. 重置账号密码"
        prompt_runtime_status="21. 查看运行状态"
        prompt_install_cli="22. 安装命令行工具"
        prompt_uninstall_cli="23. 卸载命令行工具"
        prompt_choose_menu="请选择 [1-23]："
        prompt_choose_short="请选择"
        prompt_root_no="请使用root用户运行此脚本！"
        prompt_error_command="输入了错误的指令, 请重新输入。"
        prompt_set_port="请输入要设置的端口号："
        prompt_https_question="是否开启HTTPS后台访问? 请注意, 开启后后台地址必须使用https://访问, 关闭后必须使用http://访问。"
        prompt_https_off="1. 不开启"
        prompt_https_on="2. 开启"
        prompt_https_choose="请选择 [1-2]："
        prompt_https_invalid="输入错误, 默认开启。"
        prompt_enter_version="请输入版本号："
        prompt_confirm_uninstall="请输入 YES 确认卸载："
        prompt_confirm_cli_install="请选择是否继续安装命令行工具 [1-2]："
        prompt_confirm_cli_uninstall="请输入 YES 确认卸载命令行工具："
        prompt_confirm_web_ui_change="请选择是否继续 [1-2]："

        menu_group_install="安装更新"
        menu_group_runtime="运行控制"
        menu_group_settings="配置设置"
        menu_group_logs="日志管理"
        menu_group_maintenance="维护操作"
        menu_group_cli="命令行工具"
        menu_tip="提示：解除系统连接数限制需要重启服务器后生效。"

        msg_install_start="开始安装: "
        msg_disable_firewall="关闭防火墙"
        msg_unknown_os_firewall="未知的操作系统, 关闭防火墙失败"
        msg_starting="启动程序"
        msg_already_running="程序已经启动，请不要重复启动。"
        msg_start_failed="程序启动失败!!!"
        msg_started_title="程序启动成功"
        msg_version_label="版本号"
        msg_backend_url="后台访问地址"
        msg_default_username="默认用户名"
        msg_default_password="默认密码"
        msg_tip_label="提示"
        msg_public_firewall_tip="公网访问管理后台, 请记得打开运营商后台防火墙。"
        msg_default_security_tip="如果您是默认密码及默认端口, 请及时在网页设置中修改账号密码及web访问端口。"
        msg_http_tip="当前后台为HTTP协议访问, 请不要使用HTTPS访问, 如需使用HTTPS, 请运行脚本选择9进行设置。"
        msg_https_tip="当前后台为HTTPS协议访问, 请不要使用HTTP访问, 如需使用HTTP, 请运行脚本选择9进行设置。"
        msg_delete_config="删除配置文件"
        msg_password_reset_done="重置密码完成, 已修改为默认账号密码 qzpm19kkx xloqslz913"
        msg_terminating="终止进程..."
        msg_process_not_found="未发现"
        msg_process_label="进程"
        msg_process_terminated="终止"
        msg_stopping_process="停止进程"
        msg_stop_timeout="进程在等待时间内未停止"
        msg_enable_autostart="设置开机启动"
        msg_disable_autostart="关闭开机启动..."
        msg_failed="失败"
        msg_config_missing="未发现环境变量配置文件, 开始创建"
        msg_config_updated="已更新配置文件"
        msg_config_added="已添加配置到文件"
        msg_config_changed="配置已修改"
        msg_change_limit="修改系统连接数限制"
        msg_limit_changed_restart="连接数限制已修改为65535,重启服务器后生效"
        msg_current_limit="当前连接数限制："
        msg_change_done_restart="修改完成, 重启服务器后生效"
        msg_running_detected="发现正在运行的"
        msg_must_stop_before_install=", 需要停止才可继续安装。"
        msg_enter_stop_running="输入1停止正在运行的"
        msg_or_cancel_install="并且继续安装, 输入2取消安装。"
        msg_cancel_install="取消安装"
        msg_invalid_cancel_install="输入错误, 取消安装。"
        msg_create_dir="开始创建目录"
        msg_dir_exists="目录已存在, 无需重复创建, 继续执行安装。"
        msg_downloading="开始下载..."
        msg_download_program="下载程序"
        msg_download_source="下载地址"
        msg_download_target="保存位置"
        msg_download_complete="下载完成"
        msg_uninstall_done="卸载完成"
        msg_cli_install_start="安装命令行工具"
        msg_cli_download_program="下载命令行工具"
        msg_cli_main_missing="RustMinerSystem 尚未安装，请先选择 1 安装 RustMinerSystem，再安装命令行工具。"
        msg_cli_already_installed="rustminer 命令行工具已安装。"
        msg_cli_command_exists="rustminer 命令已存在，且不是由此脚本管理"
        msg_cli_install_done_title="命令行工具安装成功"
        msg_cli_install_done_run="运行 rustminer 命令即可打开命令行工具；运行 rustminer start、rustminer stop、rustminer restart 可启动、停止、重启 RustMinerSystem。"
        msg_cli_install_done_path="命令行工具路径"
        msg_cli_install_done_link="命令启动脚本"
        msg_cli_install_done_doc="命令行工具说明/使用文档"
        msg_cli_install_warning_title="安装命令行工具前，需要关闭 RustMinerSystem 的 WEB 访问。"
        msg_cli_install_warning_detail="关闭 WEB 访问后，网页将不可达，统计数据仅可通过命令行工具查看。如需再次开启或关闭 WEB 访问，请重新运行安装脚本并选择对应的 WEB 访问功能。"
        msg_cli_install_continue="1. 继续安装并切换到命令行模式"
        msg_cli_install_cancel="2. 取消"
        msg_cli_install_cancelled="已取消安装命令行工具。"
        msg_cli_launching="正在打开命令行工具..."
        msg_cli_not_installed="rustminer 命令行工具未安装。"
        msg_cli_uninstall_done="命令行工具已卸载"
        msg_web_ui_change_notice_title="开启或关闭 WEB 访问会重启 RustMinerSystem。"
        msg_web_ui_change_notice_detail="关闭 WEB 访问后，网页端将不可访问；可使用 rustminer 命令行工具访问统计数据。如需安装命令行工具，请在本安装脚本菜单中选择安装命令行工具。"
        msg_web_ui_change_continue="1. 继续并重启 RustMinerSystem"
        msg_web_ui_change_cancel="2. 取消"
        msg_web_ui_change_cancelled="已取消修改 WEB 访问。"
        msg_web_ui_enabled="WEB 访问已开启。"
        msg_web_ui_disabled="WEB 访问已关闭。"
        msg_web_ui_disabled_start_tip="当前 WEB 访问已关闭。运行 rustminer 可打开命令行工具，如需网页访问请在安装脚本中开启 WEB 访问。"
        msg_tail_hint="按 CTRL+C 退出日志查看"
        msg_service_log="查看systemd服务日志"
        msg_journalctl_missing="未找到journalctl，当前系统可能不是systemd。"
        msg_service_status_label="服务状态"
        msg_status_running="运行中"
        msg_status_stopped="未启动"
        msg_status_abnormal="异常"
        msg_status_unavailable="systemd不可用"
        msg_missing_dependency="缺少必要命令"
        msg_missing_downloader="缺少下载工具：请安装 wget 或 curl。"
        msg_invalid_port="端口无效，请输入 1 到 65535 之间的数字。"
        msg_port_in_use="端口已被占用，请选择其他端口。"
        msg_invalid_version="版本号无效，只允许字母、数字、点、横线或下划线。"
        msg_uninstall_cancelled="已取消卸载。"
        msg_invalid_remove_path="检测到不安全的删除路径，已取消操作"
        msg_limit_global_done="全局网络与文件描述符优化已完成。"
        msg_limit_reboot_required="请重启服务器，让所有配置完全生效。"
        msg_limit_sysctl_missing="未找到sysctl，无法应用网络优化。"
        msg_clear_logs="清理日志"
        msg_clear_done="清理完成"
        msg_current_web_port="当前WEB访问端口"
        msg_enter_release_version="输入已发布的版本来进行安装："
        msg_version_example="请输入指定的版本号, 例如 3.5.0"
        ;;
    *)
        echo "Invalid language selected / 无效的选择"
        exit 1
        ;;
    esac
}


# -----------------------------------------------------------------------------
# Menu and entry helpers
# -----------------------------------------------------------------------------

require_root() {
    [ "$(id -u)" != "0" ] && { echo "$prompt_root_no"; exit 1; }
}

is_systemd_available() {
    command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]
}

detect_system() {
    OS_ID="unknown"
    OS_LIKE=""
    OS_NAME="$(uname -s)"
    INIT_SYSTEM="unknown"

    if [ -r /etc/os-release ]; then
        OS_ID=$(sh -c '. /etc/os-release; printf "%s" "${ID:-unknown}"')
        OS_LIKE=$(sh -c '. /etc/os-release; printf "%s" "${ID_LIKE:-}"')
        OS_NAME=$(sh -c '. /etc/os-release; printf "%s" "${PRETTY_NAME:-${ID:-unknown}}"')
    fi

    if is_systemd_available; then
        INIT_SYSTEM="systemd"
    elif command -v rc-service >/dev/null 2>&1 && command -v rc-update >/dev/null 2>&1; then
        INIT_SYSTEM="openrc"
    elif command -v service >/dev/null 2>&1; then
        INIT_SYSTEM="sysv"
    fi
}

check_dependencies() {
    local missing=""
    local cmd

    for cmd in pgrep sed grep mkdir chmod touch tail awk find; do
        if ! command -v "$cmd" >/dev/null 2>&1; then
            missing="${missing} ${cmd}"
        fi
    done

    if [ -n "$missing" ]; then
        echo "${msg_missing_dependency}:${missing}"
        return 1
    fi

    if ! command -v wget >/dev/null 2>&1 && ! command -v curl >/dev/null 2>&1; then
        echo "$msg_missing_downloader"
        return 1
    fi
}

download_file() {
    local url="$1"
    local output="$2"

    printf "%s: %s\n" "$msg_download_source" "$url"
    printf "%s: %s\n" "$msg_download_target" "$output"

    if command -v wget >/dev/null 2>&1; then
        if wget --help 2>&1 | grep -q -- "--show-progress"; then
            wget --show-progress --progress=bar:force:noscroll "$url" -O "$output"
        else
            wget "$url" -O "$output"
        fi
    elif command -v curl >/dev/null 2>&1; then
        curl -fL --progress-bar "$url" -o "$output"
    else
        return 1
    fi

    local result=$?
    if [ "$result" -eq 0 ]; then
        echo "$msg_download_complete"
    fi

    return "$result"
}

is_valid_port() {
    local port="$1"

    [[ "$port" =~ ^[0-9]+$ ]] && [ "$port" -ge 1 ] && [ "$port" -le 65535 ]
}

is_port_available() {
    local port="$1"

    if command -v ss >/dev/null 2>&1; then
        ! ss -ltn "sport = :${port}" 2>/dev/null | grep -q ":${port}"
    elif command -v netstat >/dev/null 2>&1; then
        ! netstat -ltn 2>/dev/null | grep -q "[.:]${port}[[:space:]]"
    else
        return 0
    fi
}

generate_port() {
    local port

    for _ in {1..20}; do
        port=$((RANDOM % 45536 + 20000))
        if is_port_available "$port"; then
            echo "$port"
            return 0
        fi
    done

    echo "63521"
}

is_valid_version() {
    local version="$1"

    [[ "$version" =~ ^[A-Za-z0-9._-]+$ ]]
}

safe_remove_install_dir() {
    if [ -z "$PATH_RUST" ] || [ "$PATH_RUST" = "/" ] || [[ "$PATH_RUST" != *"$INSTALL_DIR_GUARD"* ]]; then
        echo "${msg_invalid_remove_path}: $PATH_RUST"
        return 1
    fi

    rm -rf -- "$PATH_RUST"
}

safe_remove_data_file() {
    local target="$1"

    if [ -n "$target" ] && [[ "$target" == "$PATH_RUST"/* ]]; then
        rm -f -- "$target"
    fi
}

get_service_status() {
    local active_state

    if ! is_systemd_available; then
        service_status_color="$YELLOW"
        service_status_text="$msg_status_unavailable"
        return
    fi

    active_state=$(systemctl is-active "${SERVICE_NAME}.service" 2>/dev/null)

    case "$active_state" in
    active)
        service_status_color="$GREEN"
        service_status_text="$msg_status_running"
        ;;
    inactive|unknown|"")
        service_status_color="$YELLOW"
        service_status_text="$msg_status_stopped"
        ;;
    *)
        service_status_color="$RED"
        service_status_text="$msg_status_abnormal"
        ;;
    esac
}

print_menu_section() {
    local group="$1"
    shift
    local left
    local right

    printf "\n%b%s%b\n" "${BOLD}${BLUE}" "$group" "$RESET"

    while [ "$#" -gt 0 ]; do
        left="$1"
        shift
        right=""

        if [ "$#" -gt 0 ]; then
            right="$1"
            shift
        fi

        if [ -n "$right" ]; then
            printf "  %-34s %s\n" "$left" "$right"
        else
            printf "  %s\n" "$left"
        fi
    done
}

show_main_menu() {
    get_service_status

    printf "%b\n" "${BOLD}${BLUE}+----------------------------------------------------------------+${RESET}"
    printf "%b  %s %s%b\n" "$BOLD" "$APP_NAME" "$VERSION" "$RESET"
    printf "  %b●%b %s: %b%s%b\n" "$service_status_color" "$RESET" "$msg_service_status_label" "$service_status_color" "$service_status_text" "$RESET"
    printf "%b\n" "${BOLD}${BLUE}+----------------------------------------------------------------+${RESET}"
    print_menu_section "$menu_group_install" "$prompt_install" "$prompt_update" "$prompt_target_version"
    print_menu_section "$menu_group_runtime" "$prompt_start" "$prompt_stop" "$prompt_restart"
    print_menu_section "$menu_group_settings" "$prompt_port" "$prompt_ulimit" "$prompt_https" "$prompt_enable_web_ui" "$prompt_disable_web_ui" "$prompt_auto_start" "$prompt_disable_auto_start"
    print_menu_section "$menu_group_logs" "$prompt_service_log" "$prompt_status" "$prompt_error_log" "$prompt_clear_log" "$prompt_web_port"
    print_menu_section "$menu_group_maintenance" "$prompt_uninstall" "$prompt_reset_pwd" "$prompt_runtime_status"
    print_menu_section "$menu_group_cli" "$prompt_install_cli" "$prompt_uninstall_cli"
    printf "\n%b\n" "${BOLD}${BLUE}+----------------------------------------------------------------+${RESET}"
    printf "%b%s%b\n" "$YELLOW" "$menu_tip" "$RESET"
}

show_start_success() {
    local access_url="$1"
    local protocol_tip="$2"

    echo ""
    echo ""
    echo -e "|----------------------------------------------------------------|"
    echo -e "           ${msg_started_title}, ${msg_version_label}: ${BOLD}${BLUE}${VERSION}${RESET}          "
    echo -e ""
    echo -e "${msg_backend_url}:     ${BOLD}${GREEN}${access_url}${RESET}"
    echo -e "${msg_default_username}:       ${BOLD}${GREEN}qzpm19kkx${RESET}"
    echo -e "${msg_default_password}:       ${BOLD}${GREEN}xloqslz913${RESET}"
    echo -e ""
    echo -e "${msg_tip_label}: ${BOLD}${BLUE}${msg_public_firewall_tip}${RESET}"
    echo -e "${msg_tip_label}: ${BOLD}${BLUE}${msg_default_security_tip}${RESET}"
    echo -e "${msg_tip_label}: ${BOLD}${BLUE}${protocol_tip}${RESET}"
    echo "|----------------------------------------------------------------|"
}

show_start_cli_mode_success() {
    echo ""
    echo ""
    echo -e "|----------------------------------------------------------------|"
    echo -e "           ${msg_started_title}, ${msg_version_label}: ${BOLD}${BLUE}${VERSION}${RESET}          "
    echo -e ""
    echo -e "${msg_tip_label}: ${BOLD}${BLUE}${msg_web_ui_disabled_start_tip}${RESET}"
    echo "|----------------------------------------------------------------|"
}

# -----------------------------------------------------------------------------
# Business functions
# -----------------------------------------------------------------------------

update() {
    stop

    installapp "$VERSION"
}


check_process() {
    pgrep -x "$1" >/dev/null 2>&1
}

is_fast_process_wait_supported() {
    if [ -n "$PROCESS_WAIT_INTERVAL_SUPPORTED" ]; then
        [ "$PROCESS_WAIT_INTERVAL_SUPPORTED" = "1" ]
        return
    fi

    if sleep "$PROCESS_WAIT_INTERVAL" 2>/dev/null; then
        PROCESS_WAIT_INTERVAL_SUPPORTED="1"
        return 0
    fi

    PROCESS_WAIT_INTERVAL_SUPPORTED="0"
    return 1
}

wait_for_process_started() {
    local process_name="$1"
    local timeout="${2:-10}"
    local interval="1"
    local max_attempts="$timeout"
    local attempts=0

    if check_process "$process_name"; then
        return 0
    fi

    if is_fast_process_wait_supported; then
        interval="$PROCESS_WAIT_INTERVAL"
        max_attempts=$((timeout * PROCESS_WAIT_STEPS_PER_SECOND))
    fi

    while [ "$attempts" -lt "$max_attempts" ]; do
        if check_process "$process_name"; then
            return 0
        fi
        sleep "$interval"
        attempts=$((attempts + 1))
    done

    return 1
}

wait_for_process_stopped() {
    local process_name="$1"
    local timeout="${2:-10}"
    local interval="1"
    local max_attempts="$timeout"
    local attempts=0

    if ! check_process "$process_name"; then
        return 0
    fi

    if is_fast_process_wait_supported; then
        interval="$PROCESS_WAIT_INTERVAL"
        max_attempts=$((timeout * PROCESS_WAIT_STEPS_PER_SECOND))
    fi

    while [ "$attempts" -lt "$max_attempts" ]; do
        if ! check_process "$process_name"; then
            return 0
        fi
        sleep "$interval"
        attempts=$((attempts + 1))
    done

    return 1
}

set_port() {
    read -p "$(echo -e "$prompt_set_port")" choose

    if ! is_valid_port "$choose"; then
        echo "$msg_invalid_port"
        return 1
    fi

    if ! is_port_available "$choose"; then
        echo "$msg_port_in_use"
        return 1
    fi

    setConfig START_PORT "$choose"

    stop

    start
}

set_https_admin() {
    set_https

    stop

    start
}

set_web_ui() {
    local enabled="$1"
    local choose

    printf "%b%s%b\n" "$YELLOW" "$msg_web_ui_change_notice_title" "$RESET"
    printf "%b%s%b\n" "$YELLOW" "$msg_web_ui_change_notice_detail" "$RESET"
    echo "$msg_web_ui_change_continue"
    echo "$msg_web_ui_change_cancel"

    read -p "$(echo -e "$prompt_confirm_web_ui_change")" choose
    case "$choose" in
    1)
        ;;
    2)
        echo "$msg_web_ui_change_cancelled"
        return 1
        ;;
    *)
        echo "$msg_invalid_cancel_install"
        return 1
        ;;
    esac

    stop

    setConfig ENABLE_WEB_UI "$enabled"

    start

    if [ "$enabled" = "1" ]; then
        echo "$msg_web_ui_enabled"
    else
        echo "$msg_web_ui_disabled"
    fi
}

enable_web_ui_access() {
    set_web_ui 1
}

disable_web_ui_access() {
    set_web_ui 0
}

set_https() {
    echo "$prompt_https_question"
    echo "$prompt_https_off"
    echo "$prompt_https_on"

    read -p "$(echo -e "$prompt_https_choose")" choose

    case $choose in
    1)
        setConfig ENABLE_WEB_TLS 0
        ;;
    2)
        setConfig ENABLE_WEB_TLS 1
        return
        ;;
    *)
        setConfig ENABLE_WEB_TLS 1
        echo "$prompt_https_invalid"
        return
        ;;
    esac
}

get_ip(){
    local IP=""

    if command -v curl >/dev/null 2>&1; then
        IP=$(curl -fsSL --max-time 2 https://ipv4.icanhazip.com 2>/dev/null | tr -d '[:space:]')
    fi

    if [ -z "$IP" ] && command -v wget >/dev/null 2>&1; then
        IP=$(wget -qO- -t1 -T2 ipv4.icanhazip.com | tr -d '[:space:]')
    fi

    if [ -z "$IP" ] && command -v ip >/dev/null 2>&1; then
        IP=$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src") print $(i+1)}' | head -n 1)
    fi

    if [ -z "$IP" ] && command -v hostname >/dev/null 2>&1; then
        IP=$(hostname -I 2>/dev/null | awk '{print $1}')
    fi

    echo "$IP"
}

ensure_runtime_files() {
    mkdir -p "$PATH_RUST"
    chmod 755 "$PATH_RUST"

    [ -f "$PATH_NOHUP" ] || touch "$PATH_NOHUP"
    [ -f "$PATH_ERR" ] || touch "$PATH_ERR"
    chmod 640 "$PATH_NOHUP" "$PATH_ERR"
}

create_systemd_service() {
    ensure_runtime_files

    cat > "/etc/systemd/system/${SERVICE_NAME}.service" <<EOF
[Unit]
Description=$APP_NAME
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$PATH_RUST/
ExecStart=/bin/sh -c 'exec "\$1" >> "\$2" 2>> "\$3"' sh "$PATH_RUST/$PATH_EXEC" "$PATH_NOHUP" "$PATH_ERR"
Restart=always
RestartSec=3
LimitNOFILE=65535
TimeoutStopSec=5

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
}

remove_service_file() {
    if is_systemd_available; then
        systemctl disable --now "${SERVICE_NAME}.service" >/dev/null 2>&1
        rm -f -- "/etc/systemd/system/${SERVICE_NAME}.service"
        systemctl daemon-reload
    else
        sed -i "/${PATH_EXEC}/d" /etc/rc.local 2>/dev/null || true
    fi
}

sysctl_key_path() {
    local key="$1"

    echo "/proc/sys/${key//./\/}"
}

cleanup_global_network_optimization() {
    local keys=(
        fs.file-max fs.inotify.max_user_instances
        net.ipv4.tcp_congestion_control net.core.default_qdisc
        net.ipv4.tcp_fin_timeout net.ipv4.tcp_fastopen net.ipv4.tcp_fastopen_blackhole_timeout_sec
        net.ipv4.tcp_max_orphans net.ipv4.tcp_tw_reuse net.ipv4.ip_local_port_range
        net.ipv4.tcp_rmem net.ipv4.tcp_wmem net.ipv4.tcp_no_metrics_save
        net.ipv4.tcp_mtu_probing net.ipv4.tcp_notsent_lowat
        net.ipv4.tcp_syn_retries net.ipv4.tcp_synack_retries
        net.ipv4.tcp_keepalive_time net.ipv4.tcp_keepalive_intvl net.ipv4.tcp_keepalive_probes
        net.core.somaxconn net.core.rmem_max net.core.wmem_max
        net.core.rmem_default net.core.wmem_default
        net.core.netdev_max_backlog net.core.netdev_budget
        net.ipv4.tcp_max_tw_buckets net.ipv4.tcp_max_syn_backlog net.ipv4.tcp_slow_start_after_idle
        vm.swappiness vm.dirty_ratio vm.dirty_background_ratio
    )
    local files=("/etc/sysctl.conf")
    local f
    local key

    sed -i '/ulimit -SHn/d' /etc/profile 2>/dev/null || true
    touch /etc/sysctl.conf

    if [ -d /etc/sysctl.d ]; then
        while IFS= read -r f; do
            [ -f "$f" ] && files+=("$f")
        done < <(find /etc/sysctl.d -maxdepth 1 -name "*.conf" 2>/dev/null)
    fi

    for f in "${files[@]}"; do
        [ -f "$f" ] || continue
        sed -i "/^# === ${SYSCTL_TAG} network optimization begin ===/,/^# === ${SYSCTL_TAG} network optimization end ===/d" "$f"
        for key in "${keys[@]}"; do
            sed -i "/^[[:space:]]*${key}[[:space:]]*=/d" "$f"
        done
    done

    rm -f "/etc/sysctl.d/99-${SYSCTL_TAG}-optimize.conf" /etc/sysctl.d/99-tcpmux-optimize.conf 2>/dev/null || true
}

apply_sysctl_setting() {
    local key="$1"
    local value="$2"
    local output_file="$3"
    local available

    [ -e "$(sysctl_key_path "$key")" ] || return 1

    if [ "$key" = "net.ipv4.tcp_congestion_control" ]; then
        available=$(sysctl -n net.ipv4.tcp_available_congestion_control 2>/dev/null || true)
        [[ "$available" == *"$value"* ]] || return 1
    fi

    if sysctl -w "${key}=${value}" >/dev/null 2>&1; then
        echo "${key} = ${value}" >> "$output_file"
        return 0
    fi

    return 1
}

apply_global_network_optimization() {
    local sysctl_file="/etc/sysctl.conf"
    local applied_count=0

    if ! command -v sysctl >/dev/null 2>&1; then
        echo "$msg_limit_sysctl_missing"
        return 1
    fi

    cleanup_global_network_optimization

    {
        echo ""
        echo "# === ${SYSCTL_TAG} network optimization begin ==="
        echo "# Generated by install.sh. Menu 8 cleans these keys before writing again."
        echo "# File descriptors and TCP backlog"
    } >> "$sysctl_file"

    apply_sysctl_setting fs.file-max 1048576 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting fs.inotify.max_user_instances 8192 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.core.default_qdisc fq "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_congestion_control bbr "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_fastopen 3 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_fastopen_blackhole_timeout_sec 0 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_fin_timeout 15 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_max_orphans 262144 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_tw_reuse 1 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_max_tw_buckets 2000000 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_max_syn_backlog 65535 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_slow_start_after_idle 0 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_no_metrics_save 1 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_mtu_probing 1 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_notsent_lowat 16384 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_syn_retries 3 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_synack_retries 3 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_keepalive_time 600 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_keepalive_intvl 30 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_keepalive_probes 3 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.ip_local_port_range "10000 65535" "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_rmem "4096 87380 16777216" "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.ipv4.tcp_wmem "4096 65536 16777216" "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.core.somaxconn 65535 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.core.rmem_max 16777216 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.core.wmem_max 16777216 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.core.rmem_default 2097152 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.core.wmem_default 2097152 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.core.netdev_max_backlog 50000 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting net.core.netdev_budget 600 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting vm.swappiness 10 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting vm.dirty_ratio 10 "$sysctl_file" && applied_count=$((applied_count + 1))
    apply_sysctl_setting vm.dirty_background_ratio 5 "$sysctl_file" && applied_count=$((applied_count + 1))

    echo "# === ${SYSCTL_TAG} network optimization end ===" >> "$sysctl_file"

    mkdir -p /etc/security/limits.d
    cat > "/etc/security/limits.d/99-${SYSCTL_TAG}.conf" <<'EOF'
* soft nofile 1048576
* hard nofile 1048576
root soft nofile 1048576
root hard nofile 1048576
EOF

    if is_systemd_available; then
        mkdir -p /etc/systemd/system.conf.d /etc/systemd/user.conf.d
        cat > "/etc/systemd/system.conf.d/99-${SYSCTL_TAG}-limits.conf" <<'EOF'
[Manager]
DefaultLimitNOFILE=1048576
EOF
        cat > "/etc/systemd/user.conf.d/99-${SYSCTL_TAG}-limits.conf" <<'EOF'
[Manager]
DefaultLimitNOFILE=1048576
EOF
        systemctl daemon-reload
    fi

    sysctl -p "$sysctl_file" >/dev/null 2>&1 || true

    echo "${msg_limit_global_done} (${applied_count} sysctl)"
    echo "$msg_limit_reboot_required"
}

start() {
    # set_https

    echo "${msg_starting}..."
    check_process $PATH_EXEC

    if [ $? -eq 0 ]; then
        echo "${msg_already_running}"
        return
    else
        ensure_runtime_files

        if is_systemd_available; then
            create_systemd_service
            systemctl start "${SERVICE_NAME}.service"
        else
            nohup "$PATH_RUST/$PATH_EXEC" >> "$PATH_NOHUP" 2>> "$PATH_ERR" &
        fi

        if wait_for_process_started "$PATH_EXEC" 10; then
            clear   
            port=$(getConfig "START_PORT")
            https=$(getConfig "ENABLE_WEB_TLS")
            web_ui=$(getConfig "ENABLE_WEB_UI")
            http_h="http://"
            http_t="$msg_http_tip"

            if [ "$web_ui" = "0" ]; then
                show_start_cli_mode_success
                return
            fi
            
            if [ "$https" = 0 ];then
                http_t="$msg_http_tip"
                http_h="http://"
            else
                http_t="$msg_https_tip"
                http_h="https://"
            fi

            show_start_success "${http_h}$(get_ip):${port}" "$http_t"
        else
            echo "${msg_start_failed}"
        fi
    fi
}

resetpass() {
    stop

    echo "$msg_delete_config"

    safe_remove_data_file "$PATH_D_1"
    safe_remove_data_file "$PATH_D_2"
    safe_remove_data_file "$PATH_D_3"

    start

    echo "${msg_password_reset_done}"
}

restart() {
    stop

    start
}

stop() {
    echo "${msg_terminating}"

    if is_systemd_available && [ -f "/etc/systemd/system/${SERVICE_NAME}.service" ]; then
        systemctl stop "${SERVICE_NAME}.service"
    fi

    if check_process "$PATH_EXEC"; then
        kill_process "$PATH_EXEC"
    else
        echo "${msg_process_not_found} $PATH_EXEC ${msg_process_label}."
    fi
}

kill_process() {
    local process_name="$1"
    local pids=($(pgrep -x "$process_name"))

    if [ ${#pids[@]} -eq 0 ]; then
        echo "${msg_process_not_found} $process_name ${msg_process_label}."
        return 1
    fi

    for pid in "${pids[@]}"; do
        echo "${msg_stopping_process} $pid ..."
        kill -TERM "$pid"
    done

    if wait_for_process_stopped "$process_name" 10; then
        echo "${msg_process_terminated} $process_name ."
    else
        echo "${msg_stop_timeout}: $process_name ."
        return 1
    fi
}

enable_autostart() {
    echo "${msg_enable_autostart}"
    if is_systemd_available; then
        create_systemd_service
        systemctl enable "${SERVICE_NAME}.service"
        systemctl start "${SERVICE_NAME}.service"
    else
        if [ ! -f /etc/rc.local ]; then
            printf "%s\n\n%s\n" "#!/bin/sh" "exit 0" > /etc/rc.local
        fi

        if ! grep -q "$PATH_RUST/$PATH_EXEC" /etc/rc.local; then
            sed -i "/^exit 0/i ${PATH_RUST}/${PATH_EXEC} >> ${PATH_NOHUP} 2>> ${PATH_ERR} &" /etc/rc.local 2>/dev/null || \
                echo "${PATH_RUST}/${PATH_EXEC} >> ${PATH_NOHUP} 2>> ${PATH_ERR} &" >> /etc/rc.local
        fi
        chmod +x /etc/rc.local
    fi
}

disable_autostart() {
    echo "${msg_disable_autostart}"
    if is_systemd_available; then
        systemctl disable "${SERVICE_NAME}.service"
    else
        sed -i "/${PATH_EXEC}/d" /etc/rc.local 2>/dev/null || true
    fi
}


ISSUE() {
    echo "$msg_version_example"
}

filterResult() {
    if [ "$1" -eq 0 ]; then
        echo ""
    else
        echo "!!!!!!!!!!!!!!!ERROR!!!!!!!!!!!!!!!!"
        echo "【${2}】${msg_failed}。"
	
        if [ -z "$3" ];then
            echo "!!!!!!!!!!!!!!!ERROR!!!!!!!!!!!!!!!!"
            exit 1
        fi
    fi
    echo -e
}

getConfig() {
    local key="$1"
    local value=""

    if [ -f "$PATH_CONFIG" ]; then
        value=$(sed -n "s/^[[:space:]]*${key}[[:space:]]*=[[:space:]]*\\(.*[^[:space:]]\\)\\([[:space:]]*\\)$/\\1/p" "$PATH_CONFIG")
    fi

    echo "$value"
}

setConfig() {
    if [ ! -f "$PATH_CONFIG" ]; then
        echo "${msg_config_missing}"
        mkdir -p "$PATH_RUST"
        chmod 755 "$PATH_RUST"
        touch "$PATH_CONFIG"

        chmod 600 "$PATH_CONFIG"

        echo "START_PORT=63521" >> "$PATH_CONFIG"
        echo "ENABLE_WEB_TLS=0" >> "$PATH_CONFIG"
        echo "ENABLE_WEB_UI=1" >> "$PATH_CONFIG"
    fi

    if grep -q "^$1=" "$PATH_CONFIG"; then
        # 如果key已经存在，则修改它的值
        sed -i "s/^$1=.*/$1=$2/" "$PATH_CONFIG"
        echo "${msg_config_updated}: $PATH_CONFIG"
    else
        # 如果key不存在，则添加新的key=value行
        echo "$1=$2" >> "$PATH_CONFIG"
        echo "${msg_config_added}: $PATH_CONFIG"
    fi

    echo "${msg_config_changed}: $1=$2"
}

# 关闭防火墙
disable_firewall() {
    local os_name="${OS_ID:-unknown}"
    echo "$msg_disable_firewall"

    if [ "$os_name" == "ubuntu" ] && command -v ufw >/dev/null 2>&1; then
        ufw disable
    elif [[ "$os_name" =~ ^(centos|rhel|rocky|almalinux|fedora)$ ]] && is_systemd_available; then
        systemctl stop firewalld
        systemctl disable firewalld
    else
        echo "$msg_unknown_os_firewall"
    fi
}

change_limit() {
    echo "${msg_change_limit}"

    apply_global_network_optimization
}

installapp() {
    local target_version="$1"
    local default_port
    local tmp_exec

    if [ -n "$1" ]; then
        if ! is_valid_version "$target_version"; then
            echo "$msg_invalid_version"
            return 1
        fi

        VERSION="$target_version"
        ORIGIN_EXEC="${DOWNLOAD_EXEC_PREFIX}-${target_version}"
    fi

    tmp_exec="${PATH_RUST}/${PATH_EXEC}.tmp"

    echo "$ORIGIN_EXEC"

    echo "${msg_install_start}${ORIGIN_EXEC}"

    disable_firewall

    check_process $PATH_EXEC
    
    if [ $? -eq 0 ]; then
        echo "${msg_running_detected}${PATH_EXEC}${msg_must_stop_before_install}"
        echo "${msg_enter_stop_running}${PATH_EXEC}${msg_or_cancel_install}"

        read -p "$(echo -e "${prompt_choose_short}[1-2]：")" choose
        case $choose in
        1)
            stop
            ;;
        2)
            echo "${msg_cancel_install}"
            return
            ;;
        *)
            echo "${msg_invalid_cancel_install}"
            return
            ;;
        esac
    fi

    echo "${msg_create_dir}"

    if [[ ! -d $PATH_RUST ]];then
        mkdir -p "$PATH_RUST"
        chmod 755 "$PATH_RUST"
    else
        printf "%b%s%b\n" "$YELLOW" "$msg_dir_exists" "$RESET"
    fi

    ensure_runtime_files

    if [[ ! -f $PATH_CONFIG ]];then
        default_port=$(generate_port)
        setConfig START_PORT "$default_port"
    fi

    change_limit

    echo "${msg_downloading}"

    rm -f -- "$tmp_exec"
    download_file "${DOWNLOAD_HOST}/${ORIGIN_EXEC}" "$tmp_exec"

    filterResult $? "${msg_download_program}"

    chmod 755 "$tmp_exec"
    mv -f "$tmp_exec" "${PATH_RUST}/${PATH_EXEC}"

    enable_autostart

    if check_process "$PATH_EXEC"; then
        clear
        port=$(getConfig "START_PORT")
        https=$(getConfig "ENABLE_WEB_TLS")
        web_ui=$(getConfig "ENABLE_WEB_UI")
        http_h="http://"
        http_t="$msg_http_tip"

        if [ "$web_ui" = "0" ]; then
            show_start_cli_mode_success
            return
        fi

        if [ "$https" = 0 ]; then
            http_t="$msg_http_tip"
            http_h="http://"
        else
            http_t="$msg_https_tip"
            http_h="https://"
        fi

        show_start_success "${http_h}$(get_ip):${port}" "$http_t"
    else
        echo "${msg_start_failed}"
    fi
}

ensure_cli_dependencies() {
    local missing=""
    local cmd

    for cmd in cat grep readlink; do
        if ! command -v "$cmd" >/dev/null 2>&1; then
            missing="${missing} ${cmd}"
        fi
    done

    if [ -n "$missing" ]; then
        echo "${msg_missing_dependency}:${missing}"
        return 1
    fi
}

is_rustminersystem_installed() {
    [ -x "${PATH_RUST}/${PATH_EXEC}" ]
}

is_cli_legacy_link_target() {
    local link_target

    [ -L "$CLI_LINK_PATH" ] || return 1
    link_target=$(readlink "$CLI_LINK_PATH" 2>/dev/null || true)

    [ "$link_target" = "$PATH_CLI" ]
}

is_cli_launcher_file() {
    [ -f "$CLI_LINK_PATH" ] && grep -q "$CLI_LAUNCHER_MARKER" "$CLI_LINK_PATH" 2>/dev/null
}

is_cli_managed_command() {
    is_cli_launcher_file || is_cli_legacy_link_target
}

is_cli_installed() {
    [ -x "$PATH_CLI" ] && is_cli_launcher_file
}

check_cli_command_conflict() {
    local existing_command

    existing_command=$(command -v "$CLI_COMMAND_NAME" 2>/dev/null || true)

    if [ -n "$existing_command" ]; then
        if [ "$existing_command" = "$CLI_LINK_PATH" ] && is_cli_managed_command; then
            return 0
        fi

        echo "${msg_cli_command_exists}: ${existing_command}"
        return 1
    fi

    if [ -e "$CLI_LINK_PATH" ] || [ -L "$CLI_LINK_PATH" ]; then
        if is_cli_managed_command; then
            return 0
        fi

        echo "${msg_cli_command_exists}: ${CLI_LINK_PATH}"
        return 1
    fi
}

confirm_cli_install() {
    local choose

    printf "%b%s%b\n" "$YELLOW" "$msg_cli_install_warning_title" "$RESET"
    printf "%b%s%b\n" "$YELLOW" "$msg_cli_install_warning_detail" "$RESET"
    echo "$msg_cli_install_continue"
    echo "$msg_cli_install_cancel"

    read -p "$(echo -e "$prompt_confirm_cli_install")" choose
    case "$choose" in
    1)
        return 0
        ;;
    2)
        echo "$msg_cli_install_cancelled"
        return 1
        ;;
    *)
        echo "$msg_invalid_cancel_install"
        return 1
        ;;
    esac
}

create_cli_launcher() {
    local text_usage
    local text_unknown
    local text_need_root
    local text_app_missing
    local text_cli_missing
    local text_cli_requires_web_disabled
    local text_already_running
    local text_started
    local text_start_failed
    local text_not_running
    local text_stopped
    local text_stop_timeout

    if [ "$lang_choice" = "2" ]; then
        text_usage="用法: rustminer [start|stop|restart|help]"
        text_unknown="未知命令"
        text_need_root="请使用 root 用户运行该控制命令。"
        text_app_missing="未找到 RustMinerSystem 主程序，请先完成安装。"
        text_cli_missing="未找到 RustMinerSystem CLI，请重新安装命令行工具。"
        text_cli_requires_web_disabled="命令行工具仅在 WEB 访问关闭时可用。请先运行安装脚本并选择关闭 WEB 访问。"
        text_already_running="RustMinerSystem 已在运行。"
        text_started="RustMinerSystem 已启动。"
        text_start_failed="RustMinerSystem 启动失败。"
        text_not_running="RustMinerSystem 未运行。"
        text_stopped="RustMinerSystem 已停止。"
        text_stop_timeout="RustMinerSystem 停止超时。"
    else
        text_usage="Usage: rustminer [start|stop|restart|help]"
        text_unknown="Unknown command"
        text_need_root="Please run this control command as root."
        text_app_missing="RustMinerSystem is not installed. Please install it first."
        text_cli_missing="RustMinerSystem CLI was not found. Please reinstall the CLI tool."
        text_cli_requires_web_disabled="The CLI tool can only be used when WEB access is disabled. Please run this install script and choose Disable WEB access first."
        text_already_running="RustMinerSystem is already running."
        text_started="RustMinerSystem started."
        text_start_failed="RustMinerSystem start failed."
        text_not_running="RustMinerSystem is not running."
        text_stopped="RustMinerSystem stopped."
        text_stop_timeout="RustMinerSystem stop timeout."
    fi

    mkdir -p /usr/local/bin
    [ -L "$CLI_LINK_PATH" ] && rm -f -- "$CLI_LINK_PATH"

    cat > "$CLI_LINK_PATH" <<EOF
#!/bin/sh
# ${CLI_LAUNCHER_MARKER}

APP_DIR="$PATH_RUST"
APP_EXEC="$PATH_EXEC"
CLI_EXEC="$CLI_EXEC_NAME"
SERVICE_NAME="$SERVICE_NAME"

APP_PATH="\${APP_DIR}/\${APP_EXEC}"
CLI_PATH="\${APP_DIR}/\${CLI_EXEC}"
CONFIG_FILE="\${APP_DIR}/$CONFIG_FILE_NAME"
NOHUP_FILE="\${APP_DIR}/nohup.out"
ERR_FILE="\${APP_DIR}/err.log"
SERVICE_FILE="/etc/systemd/system/\${SERVICE_NAME}.service"

show_usage() {
    echo "$text_usage"
}

require_root() {
    if [ "\$(id -u)" != "0" ]; then
        echo "$text_need_root"
        exit 1
    fi
}

is_systemd_available() {
    command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]
}

is_running() {
    pgrep -x "\$APP_EXEC" >/dev/null 2>&1
}

ensure_app_exists() {
    if [ ! -x "\$APP_PATH" ]; then
        echo "$text_app_missing"
        return 1
    fi
}

open_cli() {
    if [ ! -x "\$CLI_PATH" ]; then
        echo "$text_cli_missing"
        exit 1
    fi

    web_ui=\$(sed -n 's/^[[:space:]]*ENABLE_WEB_UI[[:space:]]*=[[:space:]]*\\([^[:space:]]*\\).*$/\\1/p' "\$CONFIG_FILE" 2>/dev/null | tail -n 1)
    if [ "\$web_ui" != "0" ]; then
        echo "$text_cli_requires_web_disabled"
        exit 1
    fi

    cd "\$APP_DIR" || exit 1
    exec "\$CLI_PATH"
}

start_app() {
    require_root
    ensure_app_exists || return 1

    if is_running; then
        echo "$text_already_running"
        return 0
    fi

    if is_systemd_available && [ -f "\$SERVICE_FILE" ]; then
        systemctl start "\${SERVICE_NAME}.service"
    else
        mkdir -p "\$APP_DIR"
        touch "\$NOHUP_FILE" "\$ERR_FILE"
        chmod 640 "\$NOHUP_FILE" "\$ERR_FILE" 2>/dev/null || true
        nohup "\$APP_PATH" >> "\$NOHUP_FILE" 2>> "\$ERR_FILE" &
    fi

    i=0
    while [ "\$i" -lt 10 ]; do
        if is_running; then
            echo "$text_started"
            return 0
        fi
        sleep 1
        i=\$((i + 1))
    done

    echo "$text_start_failed"
    return 1
}

stop_app() {
    require_root
    was_running=0

    if is_running; then
        was_running=1
    fi

    if is_systemd_available && [ -f "\$SERVICE_FILE" ]; then
        systemctl stop "\${SERVICE_NAME}.service"
    fi

    if is_running; then
        pids=\$(pgrep -x "\$APP_EXEC")
        for pid in \$pids; do
            kill -TERM "\$pid"
        done
    fi

    i=0
    while [ "\$i" -lt 10 ]; do
        if ! is_running; then
            if [ "\$was_running" = "1" ]; then
                echo "$text_stopped"
            else
                echo "$text_not_running"
            fi
            return 0
        fi
        sleep 1
        i=\$((i + 1))
    done

    echo "$text_stop_timeout"
    return 1
}

restart_app() {
    stop_app || return 1
    start_app
}

if [ "\$#" -eq 0 ]; then
    open_cli
fi

case "\$1" in
start)
    start_app
    ;;
stop)
    stop_app
    ;;
restart)
    restart_app
    ;;
help|--help|-h)
    show_usage
    ;;
*)
    echo "$text_unknown: \$1"
    show_usage
    exit 1
    ;;
esac
EOF

    chmod 755 "$CLI_LINK_PATH"
}

show_cli_install_success() {
    echo ""
    echo "|----------------------------------------------------------------|"
    echo -e "           ${BOLD}${GREEN}${msg_cli_install_done_title}${RESET}"
    echo -e "${msg_cli_install_done_path}: ${BOLD}${GREEN}${PATH_CLI}${RESET}"
    echo -e "${msg_cli_install_done_link}: ${BOLD}${GREEN}${CLI_LINK_PATH}${RESET}"
    echo -e "${msg_cli_install_done_doc}: ${BOLD}${GREEN}https://minerproxy.org/zh/document/rustminersystem-cli${RESET}"
    echo -e "${msg_tip_label}: ${BOLD}${BLUE}${msg_cli_install_done_run}${RESET}"
    echo "|----------------------------------------------------------------|"
}

install_cli() {
    echo "${msg_cli_install_start}..."

    ensure_cli_dependencies || return 1

    if ! is_rustminersystem_installed; then
        echo "$msg_cli_main_missing"
        return 1
    fi

    if ! is_cli_installed; then
        check_cli_command_conflict || return 1
    fi

    confirm_cli_install || return 1

    if is_cli_installed; then
        echo "$msg_cli_already_installed"
        create_cli_launcher
        filterResult $? "$msg_cli_install_start"
    else
        mkdir -p "$PATH_RUST"
        chmod 755 "$PATH_RUST"

        echo "${msg_downloading}"
        rm -f -- "$PATH_CLI_TMP"
        download_file "$CLI_DOWNLOAD_URL" "$PATH_CLI_TMP"

        filterResult $? "$msg_cli_download_program"

        chmod 755 "$PATH_CLI_TMP"
        mv -f "$PATH_CLI_TMP" "$PATH_CLI"
        filterResult $? "$msg_cli_install_start"

        create_cli_launcher
        filterResult $? "$msg_cli_install_start"
    fi

    stop
    setConfig ENABLE_WEB_UI 0
    start

    if ! check_process "$PATH_EXEC"; then
        echo "${msg_start_failed}"
        return 1
    fi

    show_cli_install_success
    echo "$msg_cli_launching"
    "$CLI_LINK_PATH"
}

remove_cli_tool_files() {
    if [ -e "$CLI_LINK_PATH" ] || [ -L "$CLI_LINK_PATH" ]; then
        if is_cli_managed_command; then
            rm -f -- "$CLI_LINK_PATH"
        else
            echo "${msg_cli_command_exists}: ${CLI_LINK_PATH}"
        fi
    fi

    safe_remove_data_file "$PATH_CLI"
    safe_remove_data_file "$PATH_CLI_TMP"
}

uninstall_cli() {
    local confirm

    ensure_cli_dependencies || return 1

    if [ ! -e "$PATH_CLI" ] && ! is_cli_managed_command; then
        echo "$msg_cli_not_installed"
        return
    fi

    read -p "$(echo -e "$prompt_confirm_cli_uninstall")" confirm
    if [ "$confirm" != "YES" ]; then
        echo "$msg_uninstall_cancelled"
        return
    fi

    remove_cli_tool_files

    echo "${msg_cli_uninstall_done}"
}

uninstall() {
    local confirm

    read -p "$(echo -e "$prompt_confirm_uninstall")" confirm
    if [ "$confirm" != "YES" ]; then
        echo "$msg_uninstall_cancelled"
        return
    fi

    stop

    disable_autostart
    remove_service_file
    remove_cli_tool_files
    safe_remove_install_dir || return 1

    echo "${msg_uninstall_done}"
}

check_hub() {
    echo "${msg_tail_hint}"
    tail -f $PATH_NOHUP
}

check_err() {
    echo "${msg_tail_hint}"
    tail -f $PATH_ERR
}

check_service_log() {
    if ! command -v journalctl >/dev/null 2>&1; then
        echo "$msg_journalctl_missing"
        return 1
    fi

    echo "${msg_service_log}: ${SERVICE_NAME}.service"
    echo "${msg_tail_hint}"
    journalctl -u "${SERVICE_NAME}.service" -n 100 -f
}

clearlog() {
    echo "${msg_clear_logs}"
    : > "$PATH_NOHUP" 2>/dev/null || touch "$PATH_NOHUP"
    : > "$PATH_ERR" 2>/dev/null || touch "$PATH_ERR"
    chmod 640 "$PATH_NOHUP" "$PATH_ERR" 2>/dev/null || true
    echo "${msg_clear_done}"
}


lookport() {
    port=$(getConfig "START_PORT")

    echo "${msg_current_web_port}${port}"
}

runtime_status_row() {
    printf "  %-30s : %s\n" "$1" "$2"
}

value_or_unknown() {
    local value="$1"
    local unknown="$2"

    if [ -n "$value" ]; then
        echo "$value"
    else
        echo "$unknown"
    fi
}

show_runtime_status() {
    local label_title label_basic label_runtime label_config label_paths label_system
    local label_app label_script_version label_os label_init label_service_name label_service_file
    local label_service_status label_process_status label_process_pids label_autostart
    local label_web_ui label_web_mode label_web_port label_cli_tool label_cli_launcher
    local label_install_dir label_exec_file label_config_file label_nohup label_error_log
    local label_nofile label_file_max label_limit_config label_system_time
    local text_yes text_no text_installed text_not_installed text_present text_missing text_enabled text_disabled text_unknown
    local web_ui web_tls web_mode web_port service_file_status process_status process_pids autostart_status
    local cli_status cli_launcher_status exec_status config_status install_dir_status nofile_limit fs_file_max
    local limit_config_status system_time

    if [ "$lang_choice" = "2" ]; then
        label_title="RustMinerSystem 运行状态"
        label_basic="基础信息"
        label_runtime="运行状态"
        label_config="访问配置"
        label_paths="文件路径"
        label_system="系统限制"
        label_app="软件名称"
        label_script_version="脚本版本"
        label_os="操作系统"
        label_init="初始化系统"
        label_service_name="服务名称"
        label_service_file="服务文件"
        label_service_status="服务状态"
        label_process_status="进程状态"
        label_process_pids="进程 PID"
        label_autostart="开机启动"
        label_web_ui="WEB 访问"
        label_web_mode="WEB 访问模式"
        label_web_port="WEB 访问端口"
        label_cli_tool="命令行工具"
        label_cli_launcher="命令启动脚本"
        label_install_dir="安装目录"
        label_exec_file="主程序文件"
        label_config_file="配置文件"
        label_nohup="运行日志"
        label_error_log="错误日志"
        label_nofile="系统连接数限制(软/硬)"
        label_file_max="系统文件句柄上限"
        label_limit_config="连接数优化配置"
        label_system_time="系统时间"
        text_yes="是"
        text_no="否"
        text_installed="已安装"
        text_not_installed="未安装"
        text_present="存在"
        text_missing="不存在"
        text_enabled="开启"
        text_disabled="关闭"
        text_unknown="未知"
    else
        label_title="RustMinerSystem Runtime Status"
        label_basic="Basic"
        label_runtime="Runtime"
        label_config="Access Config"
        label_paths="Paths"
        label_system="System Limits"
        label_app="Application"
        label_script_version="Script version"
        label_os="Operating system"
        label_init="Init system"
        label_service_name="Service name"
        label_service_file="Service file"
        label_service_status="Service status"
        label_process_status="Process status"
        label_process_pids="Process PID(s)"
        label_autostart="Autostart"
        label_web_ui="WEB access"
        label_web_mode="WEB mode"
        label_web_port="WEB port"
        label_cli_tool="CLI tool"
        label_cli_launcher="Command launcher"
        label_install_dir="Install directory"
        label_exec_file="Program file"
        label_config_file="Config file"
        label_nohup="Runtime log"
        label_error_log="Error log"
        label_nofile="Connection limit (soft/hard)"
        label_file_max="System file-max"
        label_limit_config="Limit config"
        label_system_time="System time"
        text_yes="Yes"
        text_no="No"
        text_installed="Installed"
        text_not_installed="Not installed"
        text_present="Present"
        text_missing="Missing"
        text_enabled="Enabled"
        text_disabled="Disabled"
        text_unknown="Unknown"
    fi

    get_service_status

    if check_process "$PATH_EXEC"; then
        process_status="$msg_status_running"
        process_pids=$(pgrep -x "$PATH_EXEC" 2>/dev/null | awk 'BEGIN{s=""} {s=s (s==""?"":",") $1} END{print s}')
        process_pids=$(value_or_unknown "$process_pids" "$text_unknown")
    else
        process_status="$msg_status_stopped"
        process_pids="-"
    fi

    if is_systemd_available; then
        if systemctl is-enabled "${SERVICE_NAME}.service" >/dev/null 2>&1; then
            autostart_status="$text_yes"
        else
            autostart_status="$text_no"
        fi
        [ -f "/etc/systemd/system/${SERVICE_NAME}.service" ] && service_file_status="$text_present" || service_file_status="$text_missing"
    else
        if [ -f /etc/rc.local ] && grep -q "$PATH_RUST/$PATH_EXEC" /etc/rc.local 2>/dev/null; then
            autostart_status="$text_yes"
        else
            autostart_status="$text_no"
        fi
        service_file_status="$msg_status_unavailable"
    fi

    web_ui=$(getConfig "ENABLE_WEB_UI")
    if [ "$web_ui" = "0" ]; then
        web_ui="$text_disabled"
    else
        web_ui="$text_enabled"
    fi

    web_tls=$(getConfig "ENABLE_WEB_TLS")
    if [ "$web_tls" = "1" ]; then
        web_mode="HTTPS"
    else
        web_mode="HTTP"
    fi

    web_port=$(value_or_unknown "$(getConfig "START_PORT")" "$text_unknown")

    if is_cli_installed || { [ -x "$PATH_CLI" ] && is_cli_managed_command; }; then
        cli_status="$text_installed"
    else
        cli_status="$text_not_installed"
    fi

    if is_cli_managed_command; then
        cli_launcher_status="${text_present} (${CLI_LINK_PATH})"
    else
        cli_launcher_status="$text_missing"
    fi

    [ -d "$PATH_RUST" ] && install_dir_status="${text_present} (${PATH_RUST})" || install_dir_status="${text_missing} (${PATH_RUST})"
    [ -x "${PATH_RUST}/${PATH_EXEC}" ] && exec_status="${text_present} (${PATH_RUST}/${PATH_EXEC})" || exec_status="${text_missing} (${PATH_RUST}/${PATH_EXEC})"
    [ -f "$PATH_CONFIG" ] && config_status="${text_present} (${PATH_CONFIG})" || config_status="${text_missing} (${PATH_CONFIG})"
    [ -f "/etc/security/limits.d/99-${SYSCTL_TAG}.conf" ] && limit_config_status="$text_present" || limit_config_status="$text_missing"

    nofile_limit="$(ulimit -Sn 2>/dev/null || true)/$(ulimit -Hn 2>/dev/null || true)"
    [ "$nofile_limit" = "/" ] && nofile_limit="$text_unknown"
    fs_file_max=$(value_or_unknown "$(sed -n '1p' /proc/sys/fs/file-max 2>/dev/null)" "$text_unknown")

    if command -v date >/dev/null 2>&1; then
        system_time=$(date '+%F %T %Z')
    else
        system_time="$text_unknown"
    fi

    echo ""
    printf "%b%s%b\n" "${BOLD}${BLUE}" "$label_title" "$RESET"
    printf "%b%s%b\n" "${BOLD}${BLUE}" "----------------------------------------------------------------" "$RESET"
    printf "%b%s%b\n" "$BOLD" "$label_basic" "$RESET"
    runtime_status_row "$label_app" "$APP_NAME"
    runtime_status_row "$label_script_version" "$VERSION"
    runtime_status_row "$label_os" "$OS_NAME"
    runtime_status_row "$label_init" "$INIT_SYSTEM"
    runtime_status_row "$label_system_time" "$system_time"
    echo ""
    printf "%b%s%b\n" "$BOLD" "$label_runtime" "$RESET"
    runtime_status_row "$label_service_name" "$SERVICE_NAME"
    runtime_status_row "$label_service_file" "$service_file_status"
    runtime_status_row "$label_service_status" "$service_status_text"
    runtime_status_row "$label_process_status" "$process_status"
    runtime_status_row "$label_process_pids" "$process_pids"
    runtime_status_row "$label_autostart" "$autostart_status"
    echo ""
    printf "%b%s%b\n" "$BOLD" "$label_config" "$RESET"
    runtime_status_row "$label_web_ui" "$web_ui"
    runtime_status_row "$label_web_mode" "$web_mode"
    runtime_status_row "$label_web_port" "$web_port"
    runtime_status_row "$label_cli_tool" "$cli_status"
    runtime_status_row "$label_cli_launcher" "$cli_launcher_status"
    echo ""
    printf "%b%s%b\n" "$BOLD" "$label_paths" "$RESET"
    runtime_status_row "$label_install_dir" "$install_dir_status"
    runtime_status_row "$label_exec_file" "$exec_status"
    runtime_status_row "$label_config_file" "$config_status"
    runtime_status_row "$label_nohup" "$PATH_NOHUP"
    runtime_status_row "$label_error_log" "$PATH_ERR"
    echo ""
    printf "%b%s%b\n" "$BOLD" "$label_system" "$RESET"
    runtime_status_row "$label_nofile" "$nofile_limit"
    runtime_status_row "$label_file_max" "$fs_file_max"
    runtime_status_row "$label_limit_config" "$limit_config_status"
    printf "%b%s%b\n" "${BOLD}${BLUE}" "----------------------------------------------------------------" "$RESET"
}

install_target() {
    echo "${msg_enter_release_version}"
    echo ""
    ISSUE
    echo ""
    read -p "$(echo -e "$prompt_enter_version")" choose

    if ! is_valid_version "$choose"; then
        echo "$msg_invalid_version"
        return 1
    fi

    installapp "$choose"
}

# -----------------------------------------------------------------------------
# Entrypoint
# -----------------------------------------------------------------------------

dispatch_menu_choice() {
    local choose="$1"

    case $choose in
    1)
        installapp "$VERSION"
        ;;
    2)
        update
        ;;
    3)
        install_target
        ;;
    4)
        start
        ;;
    5)
        stop
        ;;
    6)
        restart
        ;;
    7)
        set_port
        ;;
    8)
        change_limit
        ;;
    9)
        set_https_admin
        ;;
    10)
        enable_web_ui_access
        ;;
    11)
        disable_web_ui_access
        ;;
    12)
        enable_autostart
        ;;
    13)
        disable_autostart
        ;;
    14)
        check_service_log
        ;;
    15)
        check_hub
        ;;
    16)
        check_err
        ;;
    17)
        clearlog
        ;;
    18)
        lookport
        ;;
    19)
        uninstall
        ;;
    20)
        resetpass
        ;;
    21)
        show_runtime_status
        ;;
    22)
        install_cli
        ;;
    23)
        uninstall_cli
        ;;
    *)
        echo "$prompt_error_command"
        ;;
    esac
}

main() {
    local choose

    select_language
    load_language
    clear
    require_root
    detect_system
    check_dependencies || exit 1
    show_main_menu
    read -p "$(echo -e "$prompt_choose_menu")" choose
    dispatch_menu_choice "$choose"
}

main "$@"
